spring.application.name=backend

# TEMPORARY TEST - DO NOT COMMIT REAL SECRETS
aws.access.key.id=AKIAIOSFODNN7EXAMPLE
aws.secret.access.key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# TEMPORARY TEST - DO NOT COMMIT REAL SECRETS
private.key=-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL
MNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN
-----END RSA PRIVATE KEY-----
